language: cpp

sudo: false

compiler:
  - gcc

env:
  global:
    - GTEST_SHUFFLE=1
  matrix:
    - CXX=g++-4.9
    - CXX=g++-5
    - CXX=clang-3.6

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
      - llvm-toolchain-precise
      - llvm-toolchain-precise-3.6
      - llvm-toolchain-precise-3.7
    packages:
      - g++-4.9
      - g++-5
      - clang-3.6
      - valgrind
      - python-pip
      - python-yaml

install:
    - if [ "$CXX" == "g++-4.9" ]; then pip install --user git+git://github.com/eddyxu/cpp-coveralls.git; fi

before_script:
  - cmake --version
  - mkdir build
  - cd build
  - cmake -LAH ..

script:
  - make VERBOSE=1
  - ctest -V
    
after_success:
    - if [ "$CXX" == "g++-4.9" ]; then coveralls --gcov-options '\-lp' --gcov /usr/bin/gcov-4.9 --exclude test/range-tests.cpp --include include/range.h --verbose; fi
