version: '{build}'
configuration:
    - release
os: Visual Studio 2015
before_build:
    - git submodule update --init --recursive
    - mkdir build
    - cd build
    - cmake .. -G "Visual Studio 14 2015"
build:
    project: C:\projects\cpp-range\build\cpp_range.sln
test_script:
    - cd C:\projects\cpp-range\build
    - ctest -C %Configuration%
