version: '{build}'
os: Visual Studio 2015
init: []
install: []
before_build:
    - git submodule update --init --recursive
build_script:
    - set PATH=C:\Program Files (x86)\MSBuild\14.0\Bin;%PATH%
    - cmake -DCMAKE_BUILD_TYPE=Release . -G "Visual Studio 14 2015"
    - cmake --build .
test_script:
    - ctest -V
