version: '{build}'
os: Visual Studio 2015
init: []
install: []
before_build:
    - git submodule update --init --recursive
build_script:
    - set PATH=C:\Program Files (x86)\MSBuild\14.0\Bin;%PATH%
    - cmake . -G "Visual Studio 14 2015" -DBUILD_SHARED_LIBS=ON
    - cmake --build . --config Release
test_script:
    - ctest -V --build-config Release
